CREATE DATABASE SITEDATA
USE SITEDATA

CREATE TABLE Sliders
(
ID INT IDENTITY PRIMARY KEY,
Title NVARCHAR(200) NOT NULL,
Text NVARCHAR(500) NOT NULL,
Image NVARCHAR(100) NOT NULL,
[Order] INT
)


CREATE TABLE Categories
(
ID INT IDENTITY PRIMARY KEY,
Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Tags
(
ID INT IDENTITY PRIMARY KEY,
Name NVARCHAR(50) NOT NULL
)

CREATE TABLE AdditionalinfoTypes
(
ID INT IDENTITY PRIMARY KEY,
Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Products
(
ID INT IDENTITY PRIMARY KEY,
Name NVARCHAR(50) NOT NUll,
Price MONEY,
CategoryId INT CONSTRAINT CAT_ID FOREIGN KEY REFERENCES Categories(ID),
DiscaountAmount DECIMAL (18,2) NOT NULL,
IsNew BIT NOT NULL,
[COUNT] INT NOT NULL,
[Desc] NVARCHAR(150) NOT NULL,
Code NVARCHAR(10) NOT NULL,
CostPrice DECIMAL(18,2)
)
	
CREATE TABLE Users
(
ID INT IDENTITY PRIMARY KEY,
FullNAME NVARCHAR(35) NOT NULL,
Email NVARCHAR(100) NOT NULL,
Image NVARCHAR(100) NOT NULL,
PasswordHash NVARCHAR(100) NOT NULL,
Address NVARCHAR(100) NOT NULL,
)

CREATE TABLE Orders 
(
ID INT IDENTITY PRIMARY KEY,
UserId	 INT NOT NULL,
CreatedAt DATETIME2,
DeliveriedAt DATETIME2,
Status INT NOT NULL,
PaymentStatus INT NOT NULL,
TotalAmount DECIMAL NOT NULL,
Address NVARCHAR(50) NOT NULL,
Email NVARCHAR(50) NOT NULL
FullName NVARCHAR(50) NOT NULL
)